apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus-example-app
  name: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-example-app
  template:
    metadata:
      labels:
       name: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: quay.io/brancz/prometheus-example-app:v0.3.0
        ports:
        - name: web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: prometheus-example-app
spec:
  type: ClusterIP
  selector:
    name: prometheus-example-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
