apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus-example-app
  name: prometheus-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-example-app
  template:
    metadata:
      labels:
       name: prometheus-example-app
    spec:
      containers:
      - name: prometheus-example-app
        image: quay.io/brancz/prometheus-example-app:v0.3.0
        ports:
        - name: web
          containerPort: 8080

Failed to create resource: Deployment.apps "prometheus-example-app" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"prometheus-example-app"}: `selector` does not match template `labels` 
