---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: prometheus-example-app
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus-example-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
 targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
