apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-servicemonitor
  labels:
    name: prometheus-example-app
spec:
  selector:
    matchLabels:
      name: prometheus-example-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
