apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: prometheus-example-app
spec:
  type: ClusterIP
  selector:
    matchLabels:
     name: prometheus-example-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
 targetPort: 8080
